### ISSUE TITLE
Documentation tracker - v2.0.0

### ISSUE THREAD

**Issue by amarthadan** [projects-beta-test-org/projects-beta-test-repo01#19]
Airnode issues that need documentation:
- [ ] https://github.com/projects-beta-test-org/projects-beta-test-repo01/issues/9
- [ ] https://github.com/projects-beta-test-org/projects-beta-test-repo01/issues/1

Corresponding docuemntation issues:
- [ ] https://github.com/projects-beta-test-org/projects-beta-test-repo02/issues/19
- [ ] https://github.com/projects-beta-test-org/projects-beta-test-repo02/issues/20
